client_app/urls.py
from django.urls import path
from . import views

app_name = "client_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("home", views.home, name="home"),
    path("restaurant/<str:res>", views.restaurant, name="restaurant"),
    path("cart", views.cart, name="cart"),
    path("place_order", views.place_order, name="place_order"),
    path("live_order", views.live_order, name="live_order"),
    path("cancel_order", views.cancel_order, name="cancel_order"),
    path("old_orders", views.old_orders, name="old_orders"),

    # API routes
    path("add_cart/<int:food_id>", views.add_cart, name="add_cart"),
    path("update_cart/<int:cart_id>", views.update_cart, name="update_cart"),
    path("remove_cart/<int:cart_id>", views.remove_cart, name="remove_cart"),
    path("sum_cart", views.sum_cart, name="sum_cart"),

]

deliveryperson_app/urls.py
from django.urls import path
from . import views

app_name = "deliveryperson_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("live_order", views.live_order, name="live_order"),
    path("delivered", views.delivered, name="delivered"),
    path("old_orders", views.old_orders, name="old_orders"),
]

food_delivery_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("client_app.urls")),
    path('delivery_person/', include("deliveryperson_app.urls")),
    path('restaurants/', include("restaurant_app.urls")),
]

deliveryperson_app/models.py
from django.db import models


# orders table
class Order(models.Model):
    restaurant = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="order_user_restaurant")
    deliveryperson = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="order_user_deliveryperson", blank=True, null=True)
    user = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="order_user")
    order = models.TextField()
    sum_order = models.DecimalField(max_digits=6, decimal_places=2)
    is_active = models.BooleanField(default=False)
    is_sent = models.BooleanField(default=False)

    def serialize(self):

        if self.deliveryperson is None:
            return {
                "id": self.id,
                "restaurant": self.restaurant.serialize(),
                "user": self.user.serialize(),
                "order": self.order,
                "sum_order": self.sum_order,
            }
        
        else:
            return {
                "id": self.id,
                "restaurant": self.restaurant.serialize(),
                "deliveryperson": self.deliveryperson.serialize(),
                "user": self.user.serialize(),
                "order": self.order,
                "sum_order": self.sum_order,
            }

deliveryperson_app/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from client_app.models import User, Cart, Old_orders
from client_app.views import restaurant
from deliveryperson_app.models import Order
from restaurant_app.models import Food


@login_required(login_url='/delivery_person/login')
def index(request):

    # check if user is client
    if request.user.is_client is True:
        return HttpResponseRedirect(reverse("client_app:index"))

    # check if user is restaurant
    if request.user.is_restaurant is True:
        return HttpResponseRedirect(reverse("restaurant_app:index"))

    return render(request, "deliveryperson_app/index.html", {
        "orders": Order.objects.filter(is_active=False)
    })


@login_required(login_url='/delivery_person/login')
def live_order(request):

    # check if user is delivery person
    if request.user.is_deliveryperson is False:
        return render(request, "deliveryperson_app/error.html", {
            "error": "you must be delivery person to access this page"
        })

    # get order
    try:
        order = Order.objects.filter(deliveryperson=request.user).first()
    except ObjectDoesNotExist:
        # if there is no order assign order to none
        order = None

    # render page with data
    return render(request, "deliveryperson_app/order.html", {
        "order": order
    })


@login_required(login_url='/delivery_person/login')
def delivered(request):

    # make sure request method post
    if request.method != "POST":
        return render(request, "deliveryperson_app/error.html", {
            "error": "Request Error"
        })

    # check if user is delivery person
    if request.user.is_deliveryperson is False:
        return render(request, "deliveryperson_app/error.html", {
            "error": "U must be delivery person to access this route"
        })

    # check if there is order
    try:
        order = Order.objects.get(deliveryperson=request.user)
    except ObjectDoesNotExist:
        return render(request, "deliveryperson_app/error.html", {
            "error": "Order error"
        })

    # move order to old orders
    old_order = Old_orders(restaurant=order.restaurant, deliveryperson=order.deliveryperson, user=order.user, order=order.order, sum_order=order.sum_order)
    old_order.save()

    # delete the order
    order.delete()

    # redirect to index
    return HttpResponseRedirect(reverse("deliveryperson_app:index"))


@login_required(login_url='/delivery_person/login')
def old_orders(request):

    # check if user is deliveryperson
    if request.user.is_deliveryperson is False:
        return render(request, "deliveryperson_app/error.html", {
            "error": "you must be delivery person to access this page"
        })

    # get old orders
    old_orders = Old_orders.objects.filter(deliveryperson=request.user)

    # render template with data
    return render(request, "deliveryperson_app/old_orders.html", {
        "old_orders": old_orders,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:

            # check if user is restaurant
            if user.is_deliveryperson is False:
                return render(request, "deliveryperson_app/error.html", {
                    "error": "U must be deliveryperson to login"
                })

            login(request, user)
            return HttpResponseRedirect(reverse("deliveryperson_app:index"))
        else:
            return render(request, "deliveryperson_app/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "deliveryperson_app/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("client_app:index"))


def register(request):
    if request.method == "POST":

        # get inputs from user
        username = request.POST["username"]
        email = request.POST["email"]
        car = request.POST["car"]
        image = request.POST.get("image", False)
        number = request.POST["number"]

        # errors cheking
        if not username or not email or not car or not image or not number:
            return render(request, "deliveryperson_app/register.html", {
                "message": "Must fill all fields"
            })


        if len(image) > 200:
            return render(request, "deliveryperson_app/register.html", {
                "message": "Image url is too long"
            })

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "deliveryperson_app/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.is_deliveryperson = True
            user.image = image
            user.car = car
            user.number = number
            user.save()
        except IntegrityError:
            return render(request, "deliveryperson_app/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("deliveryperson_app:index"))
    else:
        return render(request, "deliveryperson_app/register.html")

deliveryperson_app/templates/deliveryperson_app/error.html
{% extends "deliveryperson_app/layout.html" %}

{% block title %}
ERROR
{% endblock %}

{% block body %}

<h1 class="text-center mt-5" style="color: red;">{{ error }}</h1>

{% endblock %}

deliveryperson_app/templates/deliveryperson_app/index.html
{% extends "deliveryperson_app/layout.html" %}

{% block title %} All orders {% endblock %}

{% block body %}

{% csrf_token %}
<div class="row"><p class="text-center fs-3 mt-5" id="orders-wait">Searching for orders</p></div>
<p class="text-center text-danger"></p>
<div class="container mt-5" id="orders">
    
    {% for order in orders %}
    <div class="row order-row">
        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <img class="im-size" src="{{ order.restaurant.image }}">
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ order.restaurant.username }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p class="text-break"><span class="text-info">FROM: </span>{{ order.restaurant.address }}. <span class="text-info">TO: </span> {{ order.user.address }}.</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p class="text-break" id="order-order-{{ order.id }}">{{ order.order }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p id="sum-order-{{ order.id }}">{{ order.sum_order | usd }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <button type="submit" class="accept-btn btn btn-success" data-order="{{ order.id }}" data-res="{{ order.restaurant.id }}">Accept</button><span class="text-danger ms-3 fs-3"></span>
        </div>
    </div>
    {% endfor %}
    <input type="hidden" value="{{ request.user.id }}" id="del-id">
    <input type="hidden" value="{{ request.user }}" id="del-name">
    <input type="hidden" value="{{ request.user.image }}" id="del-img">
    <input type="hidden" value="{{ request.user.car }}" id="del-car">
    <input type="hidden" value="{{ request.user.number }}" id="del-number">
</div>










{% endblock %}

deliveryperson_app/templates/deliveryperson_app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'deliveryperson_app/styles.css' %}" rel="stylesheet">
    <script src="{% static 'deliveryperson_app/deliveryperson_app.js' %}"></script>
</head>

<body>
    {% if request.user.is_authenticated and request.user.is_deliveryperson is True %}
    <nav class="navbar navbar-expand-lg navbar-light b">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'deliveryperson_app:index' %}">Food Delivery</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'deliveryperson_app:index' %}">All orders</a>
                    <a class="nav-link active" href="{% url 'deliveryperson_app:live_order' %}">Live order</a>
                    <a class="nav-link active" href="{% url 'deliveryperson_app:old_orders' %}">Old orders</a>
                    <a class="nav-link"><strong>{{ request.user.username }}</strong></a>
                    <a class="nav-link" href="{% url 'deliveryperson_app:logout' %}">Log Out</a>
                </div>
            </div>
        </div>
    </nav>
    {% endif %}
    <div>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

deliveryperson_app/templates/deliveryperson_app/login.html
{% extends "deliveryperson_app/layout.html" %}

{% block body %}

    <h2 class="ms-4">Login</h2>

    {% if message %}
        <h2 class="text-danger mb-3 text-center">{{ message }}</h2>
    {% endif %}
    <form action="{% url 'deliveryperson_app:login' %}" method="post" class="p-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="inputusername" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="inputusername">
        </div>
        <div class="mb-3">
            <label for="inputpassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputpassword" name="password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <div class="p-4">Don't have an account? <a href="{% url 'deliveryperson_app:register' %}">Register here.</a></div>

{% endblock %}

deliveryperson_app/templates/deliveryperson_app/old_orders.html
{% extends "deliveryperson_app/layout.html" %}

{% block title %} Cart {% endblock %}


{% block body %}


<div class="container mt-5">

    {% for i in old_orders %}

    <div class="row mb-4">

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <img src="{{ i.restaurant.image }}" class="im-size">
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.restaurant.username }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p class="text-break">{{ i.order }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.sum_order | usd }}</p>
        </div>
    </div>

    {% empty %}
    <h3 class="text-center text-info">No orders go to <a href="{% url 'client_app:home' %}">home page</a> to accept orders.</h3>

    {% endfor %}

</div>






{% endblock %}

deliveryperson_app/templates/deliveryperson_app/order.html
{% extends "deliveryperson_app/layout.html" %}

{% block title %} Live order {% endblock %}


{% block body %}


{% if order %}

<div class="container mt-3 text-center fs-4">

    <div class="row">
        <img src="{{ order.restaurant.image }}" class="im-size rounded mx-auto d-block">
    </div>

    <div class="row">
        <p>{{ order.restaurant.username }}</p>
    </div>

    <div class="row">
        <p class="text-break">{{ order.order }}</p>
    </div>

    <div class="row">
        <p><span class="text-info">Restaurant Address:</span> {{ order.restaurant.address }}</p>
    </div>

    <div class="row">
        <p><span class="text-info">User Address:</span> {{ order.user.address }}</p>
    </div>

    <div class="row">
        <p>{{ order.sum_order | usd }}</p>
    </div>

    <div class="row">

        <p class="text-info  mb-3">Call the client when you get to address to deliver the food.</p>

        <p class="text-warning  fs-3 mb-2">Warning: only press this button if the food delivered to client.</p>

        <form action="{% url 'deliveryperson_app:delivered' %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-success " value="Delivered">
        </form>

    </div>

</div>
{% else %}

<h3 class="text-center text-info mt-5">No live order go to <a href="{% url 'deliveryperson_app:index' %}">All orders</a> to get order.</h3>

{% endif %}





{% endblock %}

deliveryperson_app/templates/deliveryperson_app/register.html
{% extends "deliveryperson_app/layout.html" %}

{% block body %}

    <h2 class="ms-4">Register</h2>

    {% if message %}
        <h2 class="text-danger mb-3 text-center">{{ message }}</h2>
    {% endif %}

    <form action="{% url 'deliveryperson_app:register' %}" method="post" class="p-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="inputusername" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="inputusername">
        </div>

        <div class="mb-3">
            <label for="inputemail" class="form-label">Email Address</label>
            <input type="email" name="email" class="form-control" id="inputemail">
        </div>

        <div class="mb-3">
            <label for="inputnumber" class="form-label">Phone Number</label>
            <input type="text" name="number" class="form-control" id="inputnumber">
        </div>

        <div class="mb-3">
            <label for="inputcar" class="form-label">Car</label>
            <input type="text" name="car" class="form-control" id="inputcar">
        </div>

        <div class="mb-3">
            <label for="inputimage" class="form-label">Image url</label>
            <input type="url" name="image" class="form-control" id="inputimage">
        </div>

        <div class="mb-3">
            <label for="inputpassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputpassword" name="password">
        </div>

        <div class="mb-3">
            <label for="inputrepassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="inputrepassword" name="confirmation">
        </div>

        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <div class="p-4">Already have an account? <a href="{% url 'deliveryperson_app:login' %}">Log In here.</a></div>

{% endblock %}