client_app/urls.py
from django.urls import path
from . import views

app_name = "client_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("home", views.home, name="home"),
    path("restaurant/<str:res>", views.restaurant, name="restaurant"),
    path("cart", views.cart, name="cart"),
    path("place_order", views.place_order, name="place_order"),
    path("live_order", views.live_order, name="live_order"),
    path("cancel_order", views.cancel_order, name="cancel_order"),
    path("old_orders", views.old_orders, name="old_orders"),

    # API routes
    path("add_cart/<int:food_id>", views.add_cart, name="add_cart"),
    path("update_cart/<int:cart_id>", views.update_cart, name="update_cart"),
    path("remove_cart/<int:cart_id>", views.remove_cart, name="remove_cart"),
    path("sum_cart", views.sum_cart, name="sum_cart"),

]

deliveryperson_app/urls.py
from django.urls import path
from . import views

app_name = "deliveryperson_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("live_order", views.live_order, name="live_order"),
    path("delivered", views.delivered, name="delivered"),
    path("old_orders", views.old_orders, name="old_orders"),
]

food_delivery_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("client_app.urls")),
    path('delivery_person/', include("deliveryperson_app.urls")),
    path('restaurants/', include("restaurant_app.urls")),
]

restaurant_app/urls.py
from django.urls import path
from . import views

app_name = "restaurant_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add_food", views.add_food, name="add_food"),
]

restaurant_app/models.py
from django.db import models


# restaurant food
class Food(models.Model):
    restaurant = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="food_user")
    food = models.TextField()
    image = models.URLField(max_length=200)
    des = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.food} from {self.restaurant}"

restaurant_app/views.py
from django.shortcuts import render

import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from client_app.models import User, Cart
from deliveryperson_app.models import Order
from restaurant_app.models import Food


@login_required(login_url='/restaurants/login')
def index(request):

    # check if user is client
    if request.user.is_client is True:
        return HttpResponseRedirect(reverse("client_app:index"))

    # check if user is deliveryperson
    if request.user.is_deliveryperson is True:
        return HttpResponseRedirect(reverse("deliveryperson_app:index"))

    return render(request, "restaurant_app/index.html",{
        "orders": Order.objects.filter(restaurant=request.user, is_active=True, is_sent=True)
    })


@login_required(login_url='/')
def add_food(request):

    # if request is post add food
    if request.method == "POST":

        # make sure user is resaurant
        if request.user.is_restaurant is False:
            return render(request, "restaurant_app/error.html", {
                "error": "U must be restaurant to access this page"
            })

        # get inputs from user
        food = request.POST.get("food", "")
        image = request.POST.get("image", "")
        des = request.POST.get("des", "")
        price = request.POST.get("price", "")

        # errors checking
        if not food or not price or not des or not image:
            return render(request, "restaurant_app/add_food.html", {
                "message": "Must fill all fields",
                "food": food,
                "image": image,
                "des": des,
                "price": price
            })

        if len(image) > 200:
            return render(request, "restaurant_app/add_food.html", {
                "message": "image url is too long",
                "food": food,
                "image": image,
                "des": des,
                "price": price
            })

        try:
            price = round(float(price), 2)
        except ValueError:
            return render(request, "restaurant_app/add_food.html", {
                "message": "Price must be postive digit",
                "food": food,
                "image": image,
                "des": des,
                "price": price
            })

        # add data to db
        new_food = Food(food=food, image=image, price=price, des=des, restaurant=request.user)
        new_food.save()

        # redirect to index
        return HttpResponseRedirect(reverse("restaurant_app:index"))

    # if request is get show add food page
    else:
        # make sure user is resaurant
        if request.user.is_restaurant is False:
            return render(request, "restaurant_app/error.html", {
                "error": "U must be restaurant to access this page"
            })

        return render(request, "restaurant_app/add_food.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:

            # check if user is restaurant
            if user.is_restaurant is False:
                return render(request, "restaurant_app/error.html", {
                    "error": "U must be restaurant to login"
                })

            login(request, user)
            return HttpResponseRedirect(reverse("restaurant_app:index"))
        else:
            return render(request, "restaurant_app/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "restaurant_app/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("client_app:index"))


def register(request):
    if request.method == "POST":

        # get inputs from user
        username = request.POST["username"]
        email = request.POST["email"]
        des = request.POST["des"]
        address = request.POST["address"]
        image = request.POST.get("image", False)

        # errors cheking
        if not username or not email or not des or not image or not address:
            return render(request, "restaurant_app/register.html", {
                "message": "Must fill all fields"
            })


        if len(image) > 200:
            return render(request, "restaurant_app/register.html", {
                "message": "Image url is too long"
            })

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "restaurant_app/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.is_restaurant = True
            user.image = image
            user.des = des
            user.address = address
            user.save()
        except IntegrityError:
            return render(request, "restaurant_app/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("restaurant_app:index"))
    else:
        return render(request, "restaurant_app/register.html")

restaurant_app/templates/restaurant_app/add_food.html
{% extends "restaurant_app/layout.html" %}

{% block title %} Add Food {% endblock %}


{% block body %}

{% if message %}
<h2 class="text-danger mt-3 text-center">{{ message }}</h2>
{% endif %}

<form action="{% url 'restaurant_app:add_food' %}" method="post" enctype="multipart/form-data" class="p-5">
    {% csrf_token %}

    <h2 class="mb-3">Add Food</h2>

    <div class="mb-3">
        <label for="inputfood" class="form-label">Food</label>
        <input type="text" name="food" class="form-control" id="inputfood" value="{{ food }}">
    </div>
    
    <div class="mb-3">
        <label for="inputprice" class="form-label">Price</label>
        <input type="text" name="price" class="form-control" id="inputprice" value="{{ price }}">
    </div>
    
    <div class="mb-3">
        <label for="inputdes" class="form-label">Description</label>
        <textarea type="text" name="des" class="form-control" id="inputdes">{{ des }}</textarea>
    </div>
    
    <div class="mb-3">
        <label for="inputimage" class="form-label">Image url</label>
        <input type="url" name="image" class="form-control" id="inputimage" value="{{ image }}">
    </div>

    <input class="btn btn-primary text-center" type="submit" value="Add">

</form>














{% endblock %}

restaurant_app/templates/restaurant_app/error.html
{% extends "restaurant_app/layout.html" %}

{% block title %}
ERROR
{% endblock %}

{% block body %}

<h1 class="text-center mt-5" style="color: red;">{{ error }}</h1>

{% endblock %}

restaurant_app/templates/restaurant_app/index.html
{% extends "restaurant_app/layout.html" %}

{% block title %} All Orders {% endblock %}

{% block body %}

{% if message %}
<h2 class="text-success mt-3 text-center">{{ message }}</h2>
{% endif %}

<input type="hidden" id="res-id" value="{{ request.user.id }}">
<p class="text-center fs-3 mb-4" id="orders-wait">Searching for orders</p>

<div class="container mt-5 text-center" id="orders">

    {% for i in orders %}
    <div class="order-row row">

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.id }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p class="text-break">Delivery Person: {{ i.deliveryperson.username }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto fs-3">
            <p class="text-break">{{ i.order }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.sum_order | usd }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <button class="ready-btn btn btn-danger">Ready</button>
        </div>

    </div>
    {% endfor %}

</div>












{% endblock %}

restaurant_app/templates/restaurant_app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'restaurant_app/styles.css' %}" rel="stylesheet">
    <script src="{% static 'restaurant_app/restaurant_app.js' %}"></script>
</head>

<body>
    {% if request.user.is_authenticated and request.user.is_restaurant is True %}
    <nav class="navbar navbar-expand-lg navbar-light b">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'deliveryperson_app:index' %}">Food Delivery</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'restaurant_app:index' %}">Orders</a>
                    <a class="nav-link active" href="{% url 'restaurant_app:add_food' %}">Add food</a>
                    <a class="nav-link"><strong>{{ request.user.username }}</strong></a>
                    <a class="nav-link" href="{% url 'restaurant_app:logout' %}">Log Out</a>
                </div>
            </div>
        </div>
    </nav>
    {% endif %}
    <div>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

restaurant_app/templates/restaurant_app/login.html
{% extends "restaurant_app/layout.html" %}

{% block body %}

    <h2 class="ms-4">Login</h2>

    {% if message %}
        <h2 class="text-danger mb-3 text-center">{{ message }}</h2>
    {% endif %}
    <form action="{% url 'restaurant_app:login' %}" method="post" class="p-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="inputusername" class="form-label">Restaurant Name</label>
            <input type="text" name="username" class="form-control" id="inputusername">
        </div>
        <div class="mb-3">
            <label for="inputpassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputpassword" name="password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <div class="p-4">Don't have an account? <a href="{% url 'restaurant_app:register' %}">Register here.</a></div>

{% endblock %}

restaurant_app/templates/restaurant_app/register.html
{% extends "restaurant_app/layout.html" %}

{% block body %}

    <h2 class="ms-4">Register</h2>

    {% if message %}
        <h2 class="text-danger mb-3 text-center">{{ message }}</h2>
    {% endif %}

    <form action="{% url 'restaurant_app:register' %}" method="post" class="p-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="inputusername" class="form-label">Restaurant Name</label>
            <input type="text" name="username" class="form-control" id="inputusername">
        </div>

        <div class="mb-3">
            <label for="inputemail" class="form-label">Email Address</label>
            <input type="email" name="email" class="form-control" id="inputemail">
        </div>

        <div class="mb-3">
            <label for="inputaddress" class="form-label">Address</label>
            <textarea type="text" name="address" class="form-control" id="inputaddress"></textarea>
        </div>

        <div class="mb-3">
            <label for="inputdes" class="form-label">Description</label>
            <textarea type="text" name="des" class="form-control" id="inputdes"></textarea>
        </div>

        <div class="mb-3">
            <label for="inputimage" class="form-label">Image url</label>
            <input type="url" name="image" class="form-control" id="inputimage">
        </div>

        <div class="mb-3">
            <label for="inputpassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputpassword" name="password">
        </div>

        <div class="mb-3">
            <label for="inputrepassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="inputrepassword" name="confirmation">
        </div>

        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <div class="p-4">Already have an account? <a href="{% url 'restaurant_app:login' %}">Log In here.</a></div>

{% endblock %}