client_app/urls.py
from django.urls import path
from . import views

app_name = "client_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("home", views.home, name="home"),
    path("restaurant/<str:res>", views.restaurant, name="restaurant"),
    path("cart", views.cart, name="cart"),
    path("place_order", views.place_order, name="place_order"),
    path("live_order", views.live_order, name="live_order"),
    path("cancel_order", views.cancel_order, name="cancel_order"),
    path("old_orders", views.old_orders, name="old_orders"),

    # API routes
    path("add_cart/<int:food_id>", views.add_cart, name="add_cart"),
    path("update_cart/<int:cart_id>", views.update_cart, name="update_cart"),
    path("remove_cart/<int:cart_id>", views.remove_cart, name="remove_cart"),
    path("sum_cart", views.sum_cart, name="sum_cart"),

]

deliveryperson_app/urls.py
from django.urls import path
from . import views

app_name = "deliveryperson_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("live_order", views.live_order, name="live_order"),
    path("delivered", views.delivered, name="delivered"),
    path("old_orders", views.old_orders, name="old_orders"),
]

food_delivery_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("client_app.urls")),
    path('delivery_person/', include("deliveryperson_app.urls")),
    path('restaurants/', include("restaurant_app.urls")),
]

restaurant_app/urls.py
from django.urls import path
from . import views

app_name = "restaurant_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add_food", views.add_food, name="add_food"),
]

client_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# class for users
class User(AbstractUser):

    # the following for all users
    is_restaurant = models.BooleanField(default=False)
    is_deliveryperson = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)

    # image from https://pixabay.com/
    image = models.URLField(max_length=200, default="https://cdn.pixabay.com/photo/2018/11/13/21/43/avatar-3814049_960_720.png")

    # this one for clients and restaurants
    address = models.TextField(blank=True)
    
    # this one for deliverypersons
    car = models.TextField(blank=True)

    # this one for restaurants
    des = models.TextField(blank=True)

    # this one for clients and deliverypersons
    number = models.TextField(blank=True)

    def serialize(self):
        return {
            "username": self.username,
            "email": self.email,
            "number": self.number,
            "image": self.image,
            "car": self.car,
            "address": self.address,
        }


# cart
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cart_user")
    item = models.ForeignKey('restaurant_app.Food', on_delete=models.CASCADE, related_name="cart_food")
    n = models.IntegerField()
    sum_price = models.DecimalField(max_digits=6, decimal_places=2)


# old orders
class Old_orders(models.Model):
    restaurant = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="old_orders_user_restaurant")
    deliveryperson = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="old_orders_user_deliveryperson")
    user = models.ForeignKey('client_app.User', on_delete=models.CASCADE, related_name="old_orders_user")
    order = models.TextField()
    sum_order = models.DecimalField(max_digits=6, decimal_places=2)

client_app/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register
from django.db.models import Sum

from client_app.models import Old_orders, User, Cart
from deliveryperson_app.models import Order
from restaurant_app.models import Food


@register.filter
def usd(value):
    """Format value as USD."""
    return f"${value:,.2f}"


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("client_app:home"))
    return render(request, "client_app/index.html")


@login_required(login_url='/login')
def home(request):

    # check if user is restaurant
    if request.user.is_restaurant is True:
        return HttpResponseRedirect(reverse("restaurant_app:index"))

    # check if user is deliveryperson
    if request.user.is_deliveryperson is True:
        return HttpResponseRedirect(reverse("deliveryperson_app:index"))

    # get all restaurants
    restaurantss = User.objects.filter(is_restaurant=True, is_superuser=False)
    paginator = Paginator(restaurantss, 12)
    page_number = request.GET.get('page')
    restaurants = paginator.get_page(page_number)

    return render(request, "client_app/home.html", {
        "restaurants": restaurants,
    })


@login_required(login_url='/login')
def restaurant(request, res):

    # check if user is client
    if request.user.is_client is False:
        return render(request, "client_app/error.html", {
            "error": "U must be client to access this page"
        })

    # check if restaurant exist
    try:
        restaurant = User.objects.get(username=res)
    except ObjectDoesNotExist:
        return render(request, "client_app/error.html", {
            "error": "restaurant doesn't exist"
        })

    # check if it's restaurant
    if restaurant.is_restaurant is False:
        return render(request, "client_app/error.html", {
            "error": "restaurant doesn't exist"
        })

    # get food
    food = Food.objects.filter(restaurant=restaurant)

    # render page with data
    return render(request, "client_app/restaurant_page.html", {
        "food": food,
        "restaurant": restaurant,
    })


@login_required(login_url='/login')
def cart(request):

    # check if user is client
    if request.user.is_client is False:
        return JsonResponse({"error": "You must be user to see cart items"}, status=400)

    # get user cart
    cart = Cart.objects.filter(user=request.user)

    # get sum cart price
    sum_price_cart = cart.aggregate(Sum('sum_price'))['sum_price__sum']

    # render cart page with data
    return render(request, "client_app/cart.html", {
        "cart": cart,
        "sum_price_cart": sum_price_cart,
    })


@login_required(login_url='/login')
def sum_cart(request):

    # check if user is client
    if request.user.is_client is False:
        return JsonResponse({"error": "You must be user see cart sum"}, status=400)

    # get sum of cart
    sum_cart = Cart.objects.filter(user=request.user).aggregate(Sum('n'))['n__sum']

    # if it's empty return 0
    if not sum_cart:
        sum_cart = 0

    # return sum_cart
    return JsonResponse({"sum": sum_cart}, status=201)


@login_required(login_url='/login')
def add_cart(request, food_id):

    # make sure request method post
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # check if user is client
    if request.user.is_client is False:
        return JsonResponse({"error": "You must be user to add items to cart"}, status=400)

    # check if there's n
    data = json.loads(request.body)
    nn = [n.strip() for n in data.get("n").split(",")]

    # if it's empty return error
    if nn == [""]:
        return JsonResponse({"error": "Must Provide Post n"}, status=400)

    # get n
    n = data.get("n", "")

    # make sure n and food_id is number
    if str(n).isdigit() is False or str(food_id).isdigit() is False:
        return JsonResponse({"error": f"Error1"}, status=400)
    
    n = int(n)
    food_id = int(food_id)

    # make sure n and food_id is not 0
    if n == 0 or food_id == 0:
        return JsonResponse({"error": "Error2"}, status=400)

    # make sure food exist
    try:
        food = Food.objects.get(pk=food_id)
    except ObjectDoesNotExist:
        return JsonResponse({"error": "food doesn't exist"}, status=400)

    # get user cart
    cart = Cart.objects.filter(user=request.user)

    # calculate sum
    sum_price = round(food.price * n, 2)

    # if item already in cart update n and sum
    try:
        in_cart = Cart.objects.get(user=request.user, item=food)
        in_cart.n = in_cart.n + n
        in_cart.sum_price = in_cart.sum_price + sum_price
        in_cart.save()
        return JsonResponse({"success": "Added successfully"}, status=201)
    except ObjectDoesNotExist:
        pass

    # if cart is empty add item to it
    if not cart:

        # add item to db
        item = Cart(user=request.user, item=food, n=n, sum_price=sum_price)
        item.save()

        # return success
        return JsonResponse({"success": "Added successfully"}, status=201)
    
    # if cart is not empty check if the item from the same restaurant
    else:

        # check
        if cart.first().item.restaurant.id != food.restaurant.id:
            return JsonResponse({"error": "All items in cart must be from the same restaurant."}, status=400)

        # add item to db
        item = Cart(user=request.user, item=food, n=n, sum_price=sum_price)
        item.save()

        # return success
        return JsonResponse({"success": "Added successfully"}, status=201)


@login_required(login_url='/login')
def update_cart(request, cart_id):

    # make sure request method post
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    
    # check if user is client
    if request.user.is_client is False:
        return JsonResponse({"error": "You must be user to update items in cart"}, status=400)

    # check if there's n
    data = json.loads(request.body)
    nn = [n.strip() for n in data.get("n").split(",")]

    # if it's empty return error
    if nn == [""]:
        return JsonResponse({"error": "Must Provide Post n"}, status=400)

    # get n
    n = data.get("n", "")

    # make sure n and cart_id is number
    if str(n).isdigit() is False or str(cart_id).isdigit() is False:
        return JsonResponse({"error": f"Error1"}, status=400)

    n = int(n)
    cart_id = int(cart_id)

    # make sure n and cart_id is not 0
    if n == 0 or cart_id == 0:
        return JsonResponse({"error": "Error2"}, status=400)

    # make sure cart item exist
    try:
        cart_item = Cart.objects.get(pk=cart_id)
    except ObjectDoesNotExist:
        return JsonResponse({"error": "food is not in cart"}, status=400)

    # calculate sum
    sum_price = round(cart_item.item.price * n, 2)

    # update db
    cart_item.n = n
    cart_item.sum_price = sum_price
    cart_item.save()

    # get sum of cart
    sum_cart = Cart.objects.filter(user=request.user).aggregate(Sum('sum_price'))['sum_price__sum']

    # return success
    return JsonResponse({"success": "Updated successfully", "sum_cart": sum_cart, "sum_price": usd(cart_item.sum_price)}, status=201)


@login_required(login_url='/login')
def remove_cart(request, cart_id):

    # make sure request method post
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # check if user is client
    if request.user.is_client is False:
        return JsonResponse({"error": "You must be user to delete items from cart"}, status=400)

    # make cart_id is number
    if str(cart_id).isdigit() is False:
        return JsonResponse({"error": f"Error1"}, status=400)

    cart_id = int(cart_id)

    # cart_id is not 0
    if cart_id == 0:
        return JsonResponse({"error": "Error2"}, status=400)

    # make sure cart item exist
    try:
        cart_item = Cart.objects.get(pk=cart_id)
    except ObjectDoesNotExist:
        return JsonResponse({"error": "food is not in cart"}, status=400)

    # delete from db
    cart_item.delete()

    # get sum of cart
    sum_cart = Cart.objects.filter(user=request.user).aggregate(Sum('n'))['n__sum']

    # if cart is empty return 0
    if not sum_cart:
        sum_cart = 0

    # return success
    return JsonResponse({"success": "Removed successfully", "sum_cart": sum_cart}, status=201)


@login_required(login_url='/login')
def place_order(request):

    # make sure request method post
    if request.method != "POST":
        return render(request, "client_app/error.html", {
            "error": "Request Error"
        })
    
    # check if user is client
    if request.user.is_client is False:
        return render(request, "client_app/error.html", {
            "error": "U must be client to access this page"
        })

    # check if there is already order
    try:
        Order.objects.get(user=request.user)
        return render(request, "client_app/error.html", {
            "error": "there is already order in pending please wait for order to end or cancel order if possible"
        })
    except ObjectDoesNotExist:
        pass

    # get user cart

client_app/templates/client_app/cart.html
{% extends "client_app/layout.html" %}

{% block title %} Cart {% endblock %}


{% block body %}



<div class="container mt-5">

    <div id="empty"></div>
{% for i in cart %}
    <div class="cart-item row mb-4" id="cart-item-{{ i.id }}">

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <img src="{{ i.item.image }}" class="im-size">
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.item.food }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.item.price | usd }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p id="sum-price-{{ i.id }}">{{ i.sum_price | usd }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <div>
                <input type="hidden" value="{{ i.id }}">
                <input type="number" class="update-number-input btn text-center" min="1" value="{{ i.n }}">
                <p></p>
                {% csrf_token %}
            </div>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <div>
                <input type="hidden" value="{{ i.id }}">
                <input type="button" class="remove-button btn btn-danger" value="Remove">
                <p></p>
                {% csrf_token %}
            </div>
        </div>
    </div>
{% endfor %}

{% if cart %}
<div id="place-order" class="container">
    <h3 class="text-center mt-5" id="sum-price-cart">{{ sum_price_cart | usd }}</h3>

    <form class="text-center mt-3" action="{% url 'client_app:place_order' %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-primary btn-lg" value="Preview Order">
    </form>
</div>

{% else %}
<h3 class="text-center text-info">Cart is empty go to <a href="{% url 'client_app:home' %}">home page</a> to add items.</h3>
{% endif %}

</div>






{% endblock %}

client_app/templates/client_app/error.html
{% extends "client_app/layout.html" %}

{% block title %}
ERROR
{% endblock %}

{% block body %}

<h1 class="text-center mt-5" style="color: red;">{{ error }}</h1>

{% endblock %}

client_app/templates/client_app/home.html
{% extends "client_app/layout.html" %}

{% block title %} Home {% endblock %}


{% block body %}


<div class="container mt-5">
    <div class="row row-cols-lg-3 row-cols-sm-1">

        {% for i in restaurants %}
        <div class="col p-4 text-center">
            <a href="{% url 'client_app:restaurant' i.username %}"><img src="{{ i.image }}" class="mb-3 im-size"></a>
            <p><a href="{% url 'client_app:restaurant' i.username %}" class="a fs-3">{{ i.username }}</a></p>
            <p class="text-break mb-2">{{ i.des }}</p>
            <p class="fw-light text-break">{{ i.address }}</p>
        </div>
        {% endfor %}

    </div>
</div>


<!--Pages-->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">

        <!--Previous button-->
        {% if restaurants.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Next">
                <span aria-hidden="true">&laquo; &laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ restaurants.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&laquo; &laquo;</span>
        </li>
        <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
        </li>
        {% endif %}

        <!--page numbers-->
        {% for num in restaurants.paginator.page_range %}
        {% if num == restaurants.number %}
        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
        {% endfor %}

        <!--Next button-->
        {% if restaurants.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ restaurants.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ restaurants.paginator.num_pages }}" aria-label="Next">
                <span aria-hidden="true">&raquo; &raquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&raquo;</span>
        </li>
        <li class="page-item disabled">
            <span class="page-link">&raquo; &raquo;</span>
        </li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

client_app/templates/client_app/index.html
{% extends "client_app/layout.html" %}

{% block title %} Index {% endblock %}


{% block body %}
<section>
<div id="pixs" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#pixs" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#pixs" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#pixs" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active fw-bolder">
            <img src="https://cdn.pixabay.com/photo/2018/10/22/22/18/steak-3766548_960_720.jpg" class="im-index d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3 class="mb-3">Start oredring food</h3>
                <div class="mb-3"><span class="me-3"><a href="{% url 'client_app:register' %}"><button class="btn btn-success">Create new account</button></a></span> Or <span class="ms-3"><a href="{% url 'client_app:login' %}"><button class="btn btn-success">Login</button></a></span></div>
                <h3 class="mb-3">If you have restaurant</h3>
                <a href="{% url 'restaurant_app:login' %}"><button class="btn btn-success mb-3">Restaurant Page</button></a>
                <h3 class="mb-3">If you are intersting in deliver</h3>
                <a href = "{% url 'deliveryperson_app:login' %}"><button class="btn btn-success">Delivery person page</button></a>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://cdn.pixabay.com/photo/2017/10/15/11/41/sushi-2853382_960_720.jpg" class="im-index d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3 class="mb-3">Start oredring food</h3>
                <div class="mb-3"><span class="me-3"><a href="{% url 'client_app:register' %}"><button class="btn btn-success">Create new account</button></a></span> Or <span class="ms-3"><a href="{% url 'client_app:login' %}"><button class="btn btn-success">Login</button></a></span></div>
                <h3 class="mb-3">If you have restaurant</h3>
                <a href="{% url 'restaurant_app:login' %}"><button class="btn btn-success mb-3">Restaurant Page</button></a>
                <h3 class="mb-3">If you are intersting in deliver</h3>
                <a href = "{% url 'deliveryperson_app:login' %}"><button class="btn btn-success">Delivery person page</button></a>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="im-index d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3 class="mb-3">Start oredring food</h3>
                <div class="mb-3"><span class="me-3"><a href="{% url 'client_app:register' %}"><button class="btn btn-success">Create new account</button></a></span> Or <span class="ms-3"><a href="{% url 'client_app:login' %}"><button class="btn btn-success">Login</button></a></span></div>
                <h3 class="mb-3">If you have restaurant</h3>
                <a href="{% url 'restaurant_app:login' %}"><button class="btn btn-success mb-3">Restaurant Page</button></a>
                <h3 class="mb-3">If you are intersting in deliver</h3>
                <a href = "{% url 'deliveryperson_app:login' %}"><button class="btn btn-success">Delivery person page</button></a>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#pixs"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#pixs"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

{% endblock %}

client_app/templates/client_app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'client_app/styles.css' %}" rel="stylesheet">
    <script src="{% static 'client_app/client_app.js' %}"></script>
</head>

<body>
    {% if request.user.is_authenticated and request.user.is_client is True %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'client_app:index' %}">Food Delivery</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'client_app:index' %}">Home</a>
                    <a class="nav-link active" href="{% url 'client_app:live_order' %}">Live order</a>
                    <a class="nav-link active" href="{% url 'client_app:old_orders' %}">Old orders</a>
                    <a class="nav-link"><strong>{{ request.user.username }}</strong></a>
                    <a class="nav-link" href="{% url 'client_app:logout' %}">Log Out</a>
                </div>
            </div>
            <a href="{% url 'client_app:cart' %}" class="p-2 me-2">
                <button type="button" class="btn btn-light position-relative rounded-pill">
                    <img src="{% static 'client_app/cart.png' %}" class="img-fluid cart">
                    <span id="cart" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">0</span>
                </button>
            </a>
        </div>
    </nav>
    {% endif %}
    <div>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

client_app/templates/client_app/login.html
{% extends "client_app/layout.html" %}

{% block body %}

    <h2 class="ms-4">Login</h2>

    {% if message %}
        <h2 class="text-danger mb-3 text-center">{{ message }}</h2>
    {% endif %}
    <form action="{% url 'client_app:login' %}" method="post" class="p-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="inputusername" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="inputusername">
        </div>
        <div class="mb-3">
            <label for="inputpassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputpassword" name="password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <div class="p-4">Don't have an account? <a href="{% url 'client_app:register' %}">Register here.</a></div>

{% endblock %}

client_app/templates/client_app/old_orders.html
{% extends "client_app/layout.html" %}

{% block title %} Cart {% endblock %}


{% block body %}


<div class="container mt-5">

    {% for i in old_orders %}

    <div class="row mb-4">

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <img src="{{ i.restaurant.image }}" class="im-size">
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.restaurant.username }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.deliveryperson }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p class="text-break">{{ i.order }}</p>
        </div>

        <div class="col col-lg-2 col-sm-auto col-xs-auto">
            <p>{{ i.sum_order | usd }}</p>
        </div>
    </div>

    {% empty %}
    <h3 class="text-center text-info">No orders go to <a href="{% url 'client_app:home' %}">home page</a> to order.</h3>

    {% endfor %}

</div>






{% endblock %}

client_app/templates/client_app/register.html
{% extends "client_app/layout.html" %}

{% block body %}

    <h2 class="ms-4">Register</h2>

    {% if message %}
        <h2 class="text-danger mb-3 text-center">{{ message }}</h2>
    {% endif %}

    <form action="{% url 'client_app:register' %}" method="post" class="p-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="inputusername" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="inputusername">
        </div>

        <div class="mb-3">
            <label for="inputemail" class="form-label">Email Address</label>
            <input type="email" name="email" class="form-control" id="inputemail">
        </div>

        <div class="mb-3">
            <label for="inputnumber" class="form-label">Phone Number</label>
            <input type="text" name="number" class="form-control" id="inputnumber">
        </div>

        <div class="mb-3">
            <label for="inputaddress" class="form-label">Address</label>
            <textarea type="text" name="address" class="form-control" id="inputaddress"></textarea>
        </div>

        <div class="mb-3">
            <label for="inputimage" class="form-label">Image url <span class="text-info">optionally</span></label>
            <input type="url" name="image" class="form-control" id="inputimage">
        </div>

        <div class="mb-3">
            <label for="inputpassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputpassword" name="password">
        </div>

        <div class="mb-3">
            <label for="inputrepassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="inputrepassword" name="confirmation">
        </div>

        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <div class="p-4">Already have an account? <a href="{% url 'client_app:login' %}">Log In here.</a></div>

{% endblock %}

client_app/templates/client_app/restaurant_page.html
{% extends "client_app/layout.html" %}


{% block title %} {{ restaurant.username }} {% endblock %}


{% block body %}

<div class="container mt-5">

    <div class="row mb-4 text-center">
        <img src="{{ restaurant.image }}" class="im-size2 rounded mx-auto d-block mb-3">
        <h1>{{ restaurant.username }}</h1>
        <p class="text-break mt-2 fs-4">{{ restaurant.des }}</p>
    </div>

    <div class="row row-cols-lg-2 row-cols-sm-1">

        {% for i in food %}
        <div class="col p-5 ">
            <img src="{{ i.image }}" class="im-size mb-3 rounded mx-auto d-block">
            <p class="fs-3">{{ i.food }}</p>
            <p>{{ i.price | usd }}</p>
            <p class="text-break mb-4">{{ i.des }}</p>
            <input type="hidden" value="{{ i.id }}">
            <input type="button" class="add-button btn btn-primary me-3" value="Add to cart">
            <input type="number" class="number-input btn text-center" min="1" value="1">
            <p></p>
            {% csrf_token %}
        </div>
        
        {% endfor %}
    </div>
</div>
















{% endblock %}